# Generated by Django 4.2.1 on 2023-11-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0008_operationdetails_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicraci',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historicraci',
            name='m_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
