# Generated by Django 4.2.1 on 2023-11-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0009_alter_historicraci_file_alter_historicraci_m_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='m_objectif_indi',
            field=models.TextField(blank=True, default='true', null=True),
        ),
    ]
