# Generated by Django 4.2.1 on 2023-11-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0010_alter_indicateur_m_objectif_indi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationconsulted',
            name='m_stars',
        ),
    ]
