# Generated by Django 4.2.1 on 2023-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0011_remove_operationconsulted_m_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicraci',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
