# Generated by Django 4.2.1 on 2023-12-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0012_historicraci_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationconsulted',
            name='email1',
            field=models.CharField(max_length=58, null=True),
        ),
        migrations.AddField(
            model_name='operationconsulted',
            name='email2',
            field=models.CharField(max_length=58, null=True),
        ),
        migrations.AddField(
            model_name='operationconsulted',
            name='email3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operationconsulted',
            name='email4',
            field=models.CharField(max_length=59, null=True),
        ),
    ]
