# Generated by Django 3.2.12 on 2024-03-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0013_operationconsulted_email1_operationconsulted_email2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='sexe',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
