# Generated by Django 3.2.12 on 2024-12-09 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctn_bpf', '0014_auto_20240321_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.FileField(blank=True, null=True, upload_to='')),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baniere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='m_periode',
        ),
        migrations.RemoveField(
            model_name='operationrapport',
            name='period',
        ),
        migrations.AddField(
            model_name='dataset',
            name='periodicite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.periode'),
        ),
        migrations.AddField(
            model_name='dset_delt',
            name='date_saisie',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='type_aggregation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insitutionentities',
            name='dataset',
            field=models.ManyToManyField(to='ctn_bpf.DataSet'),
        ),
        migrations.AddField(
            model_name='institution',
            name='categorie_op',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='formulaire',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='nature',
            field=models.CharField(blank=True, default=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='ponderation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='dataset',
            field=models.ManyToManyField(null=True, to='ctn_bpf.DataSet'),
        ),
        migrations.AddField(
            model_name='operation',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='montant3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='periode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure'),
        ),
        migrations.AddField(
            model_name='operationrapport',
            name='etat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ctn_bpf.structure'),
        ),
        migrations.AlterField(
            model_name='dset_delt',
            name='m_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='m_datalets_calcul',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='m_denominateur',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='m_enti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.entity'),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='m_numerateur',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='m_unite',
            field=models.CharField(blank=True, default='%', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='m_verification_indi',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='default_options',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='sigle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='accountable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountable', to='ctn_bpf.personnel'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='consulted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulted', to='ctn_bpf.personnel'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='informed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informed', to='ctn_bpf.personnel'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='m_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='nom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.personnel'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sexe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SousActualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='generate_filename')),
                ('documents', models.FileField(blank=True, null=True, upload_to='generate_filename')),
                ('actualite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.actualite')),
                ('baniere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.baniere')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Rubrique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('rubrique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.rubrique')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.categorie')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeOk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('numero_ordre', models.IntegerField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('periodicite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.periode')),
            ],
        ),
        migrations.CreateModel(
            name='NatureOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.CreateModel(
            name='MasterGroupe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.CreateModel(
            name='MasterElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('element', models.ManyToManyField(to='ctn_bpf.DataElement')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('master', models.ManyToManyField(to='ctn_bpf.Master')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.AddField(
            model_name='master',
            name='master_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.mastergroupe'),
        ),
        migrations.CreateModel(
            name='IndicateurValeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_donnee', models.CharField(blank=True, max_length=255, null=True)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('date_saisie', models.DateField(null=True)),
                ('indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.indicateur')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('periode_ok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.periodeok')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.structure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('structure', models.ManyToManyField(to='ctn_bpf.Structure')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='GroupeIndicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('indicateur', models.ManyToManyField(to='ctn_bpf.Indicateur')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('element', models.ManyToManyField(to='ctn_bpf.DataElement')),
            ],
        ),
        migrations.CreateModel(
            name='DataAccreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('aire', models.TextField(blank=True, null=True)),
                ('fosa', models.TextField(blank=True, null=True)),
                ('status_fosa', models.TextField(max_length=255, null=True)),
                ('fonction', models.TextField(blank=True, null=True)),
                ('thematique', models.TextField(blank=True, null=True)),
                ('critere', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('critere_consensus', models.TextField(blank=True, null=True)),
                ('poids', models.IntegerField(blank=True, null=True)),
                ('pas_du_tout_noter_0', models.IntegerField(blank=True, null=True)),
                ('partiel_noter_1', models.IntegerField(blank=True, null=True)),
                ('entierement_noter_2', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('total_max', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('user_ip', models.CharField(max_length=45)),
                ('consultation_datetime', models.DateTimeField()),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=255)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, null=True)),
                ('format_fichier', models.CharField(max_length=255, null=True)),
                ('auteur', models.CharField(max_length=255, null=True)),
                ('date_enregistrement', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=255, null=True)),
                ('source_financement', models.CharField(blank=True, max_length=255, null=True)),
                ('provenance', models.TextField(blank=True, null=True)),
                ('index', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.categorie')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution')),
                ('sous_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.sous_categorie')),
            ],
        ),
        migrations.AddField(
            model_name='actualite',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='rubrique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.rubrique'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='sous_rubrique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.sous_rubrique'),
        ),
        migrations.AddField(
            model_name='dset_delt',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.periodeok'),
        ),
        migrations.AddField(
            model_name='institution',
            name='baniere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.baniere'),
        ),
        migrations.AddField(
            model_name='institution',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.groupe_institution'),
        ),
        migrations.AddField(
            model_name='operation',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.categorieoperation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='nature_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.natureoperation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='periode_ok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.periodeok'),
        ),
    ]
