# Generated by Django 4.2.17 on 2025-04-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
