# Generated by Django 4.2.17 on 2025-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0002_institution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
