# Generated by Django 4.2.17 on 2025-05-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0005_actualite_prix_alter_actualite_id_alter_aggregate_id_and_more'),
    ]

    operations = [
    ]
