# Generated by Django 4.2.17 on 2025-05-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0006_add_uuids_to_ctn_bpf_institution'),
    ]

    operations = [
    ]
