# Generated by Django 4.2.17 on 2025-05-08 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0007_add_uuids_to_ctn_bpf_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
