# Generated by Django 4.2.17 on 2025-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0008_institution_uuid_alter_institution_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
