# Generated by Django 4.2.17 on 2025-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0009_remove_institution_uuid_alter_institution_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='purpose',
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
