# Generated by Django 4.2.17 on 2025-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0010_remove_institution_purpose_institution_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
        migrations.AddField(
            model_name='institution',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
