# Generated by Django 4.2.17 on 2025-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0011_remove_institution_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
