# Generated by Django 4.2.17 on 2025-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0012_institution_address_institution_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
