# Generated by Django 4.2.17 on 2025-05-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0013_institution_email_alter_institution_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actualite',
            index=models.Index(fields=['institution', 'intitule', 'prix'], name='institutions_index'),
        ),
    ]
