# Generated by Django 4.2.17 on 2025-05-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0014_actualite_institutions_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sousactualite',
            index=models.Index(fields=['intitule', 'actualite', 'institution', 'prix'], name='index_sous_actualite'),
        ),
    ]
