# Generated by Django 4.2.17 on 2025-06-04 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0015_sousactualite_index_sous_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctn_bpf.institution'),
        ),
    ]
