# Generated by Django 4.2.17 on 2025-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0016_institution_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
