# Generated by Django 4.2.17 on 2025-06-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0017_institution_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='partenaires',
            field=models.ManyToManyField(blank=True, to='ctn_bpf.institution'),
        ),
    ]
