# Generated by Django 4.2.17 on 2025-06-12 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0018_institution_partenaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='sous_rubrique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='ctn_bpf.sous_rubrique'),
        ),
    ]
