# Generated by Django 4.2.17 on 2025-06-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctn_bpf', '0019_alter_actualite_sous_rubrique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='ctn_bpf.institution'),
        ),
    ]
